# [train, eval, inference]
mode: eval
device: cuda
pretrained: ./experiments/Unet_resnet34_0/models/best_Unet.pth
metrics: {types: [f_score, precision, recall, iou_score],
          threshold: 0.5}
model: {base: Unet, encoder_name: resnet34,
        encoder_weights: null, in_channels: 3, classes: 2}
data: {all_in_memory: True, datapath: ./dataset,
       mean: [114.6, 119.5, 128.6], std: [77.8, 76.0, 78.2],
       image_size: [800, 800], mask_channel: 2}